CREATE DATABASE LIVESPREAD_DK ON (FILENAME = "/var/opt/mssql/data/LIVESPREAD_DK.mdf"), (FILENAME = "/var/opt/mssql/data/LIVESPREAD_DK_log.ldf") FOR ATTACH;
CREATE DATABASE PLATFORM_DK ON (FILENAME = "/var/opt/mssql/data/PLATFORM_DK.mdf"), (FILENAME = "/var/opt/mssql/data/PLATFORM_DK_log.ldf") FOR ATTACH;
CREATE DATABASE UIC_DK ON (FILENAME = "/var/opt/mssql/data/UIC_DK.mdf"), (FILENAME = "/var/opt/mssql/data/UIC_DK_log.ldf") FOR ATTACH;

CREATE LOGIN LIVESPREAD  WITH PASSWORD = 'sdjv123vHDS@#HGV';
CREATE LOGIN PLATFORMDB WITH PASSWORD = 'sdjv123vHDS@#HGV';
CREATE LOGIN UIC WITH PASSWORD = 'sdjv123vHDS@#HGV';

--CREATE USER LIVESPREAD FOR LOGIN LIVESPREAD;  
--CREATE LOGIN RAGEV15 WITH PASSWORD = 'sdjv123vHDS@#HGV';  
--CREATE USER RAGEV15 FOR LOGIN RAGEV15;  
--CREATE LOGIN UIC WITH PASSWORD = 'sdjv123vHDS@#HGV';  
--CREATE USER UIC FOR LOGIN UIC;




--ALTER USER [LIVESPREAD] WITH DEFAULT_SCHEMA=[dbo];
--ALTER USER [RAGEV15] WITH DEFAULT_SCHEMA=[dbo];
--ALTER USER [UIC] WITH DEFAULT_SCHEMA=[dbo];

--USE LIVESPREAD_CO
--GO
--EXEC sp_change_users_login 'AUTO_FIX', 'LIVESPREAD';

--USE RAGEV15_CO
--EXEC sp_change_users_login 'AUTO_FIX', 'RAGEV15';

--USE UIC
--EXEC sp_change_users_login 'AUTO_FIX', 'UIC';




--CREATE USER LIVESPREAD WITH PASSWORD = 'sdjv123vHDS@#HGV';
--CREATE USER RAGEV15 WITH PASSWORD = 'sdjv123vHDS@#HGV';
--CREATE USER UIC WITH PASSWORD = 'sdjv123vHDS@#HGV';
