USE [LIVESPREAD_V1]
GO
CREATE USER [LIVESPREAD] FOR LOGIN [LIVESPREAD]
GO
USE [LIVESPREAD_V1]
GO
ALTER ROLE [db_owner] ADD MEMBER [LIVESPREAD]
GO

USE [PLATFORM_V1]
GO
CREATE USER [PLATFORMDB] FOR LOGIN [PLATFORMDB]
GO
USE [PLATFORM_V1]
GO
ALTER ROLE [db_owner] ADD MEMBER [PLATFORMDB]
GO

USE [UIC_V1]
GO
CREATE USER [UIC] FOR LOGIN [UIC]
GO
USE [UIC_V1]
GO
ALTER ROLE [db_owner] ADD MEMBER [UIC]
GO

USE [LIVESPREAD_V1]
GO
EXEC sp_change_users_login 'AUTO_FIX', 'LIVESPREAD';
GO
USE [PLATFORM_V1]
GO
EXEC sp_change_users_login 'AUTO_FIX', 'PLATFORMDB';
GO
USE [UIC_V1]
GO
EXEC sp_change_users_login 'AUTO_FIX', 'UIC';
GO


