version: '3'
services: 
  cora-mssql:
    image: "370913028188.dkr.ecr.us-east-1.amazonaws.com/cora-mssql:2.0"
    ports:
      - "1433:1433"
#    volumes:
#      - mssql:/var/opt/mssql    
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "B@TMAN206"

  cora-livespread:
    image: "370913028188.dkr.ecr.us-east-1.amazonaws.com/cora-livespread:latest"
    depends_on:
      - cora-mssql
    ports:
      - "8080:8080"
    volumes:
      - /var/lib/docker/volumes/config-files/_data/input.properties:/usr/local/tomcat/webapps/input.properties

  cora-platform:
    image: "370913028188.dkr.ecr.us-east-1.amazonaws.com/cora-platform:latest"
    depends_on:
      - cora-livespread
    ports:
      - "8081:8081"
      - "9990:9990"
      - "9993:9993"      
    volumes:
      - /var/lib/docker/volumes/config-files/_data/standalone-full.xml:/opt/jboss/wildfly/standalone/configuration/standalone-full.xml
      
volumes:
#  mssql:  
  config-files:  
